### ISSUE TITLE
Stuck on "Resizing SD card partitions, please wait"

### ISSUE THREAD

**Issue by PolestarWorkshop** [octathorp/m17_tools#2]
Hello! I'm tried your firmware on my M17 device. Installed on 8 gb microsd, and fresh 16 gb card, everytime i'm stuck on message "Resizing SD card partitions, please wait"... Tried to wait about 2 hours and no luck... Received device today, buyed about 2-3 weeks ago.

**Comment by octathorp** [comment]
Sorry for the late reply.

Make sure you are using a known good SD card, class 10 or better (UHS).

Also, it's possible this is being caused by your M17 being an unknown or new hardware revision, but as stated on the release notes this project is not going to be updated nor maintained, as it has been superceded by Batocera/Koriki port.
